name: CICD Pipeline

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Enter the version (eg: v1.0.0)"
        required: true

env:
  IMAGE_NAME: skillexchange

jobs:
  continous-integration:
    name: Build Image and Push to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }} .

      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }}